name = "ares-portfolio"
pages_build_output_dir = "."

# Data de compatibilidade para o runtime do Pages
compatibility_date = "2026-07-29"

# Conexão com o seu banco D1
[[d1_databases]]
binding = "DB"
database_name = "ares"
database_id = "8d7771a9-8760-4418-983d-a9f6eacc5a77"
